name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install
      run: |
        npm install -g yarn
        yarn install
    - name: Test
      run: |
        yarn test
      env:
        CI: true
    - name: Coverage
      run: |
        yarn coverage
